version: '3.5'
services:
  api1: 
    build:
      context: .
    hostname: api1
    depends_on:
      - db
    expose:
      - "4000"
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db/rinha_backend_dev
      - SECRET_KEY_BASE=4kZGFFt1SKlRnExAsUKG7aSpJCo2bsyA5smXYNJfe0EbqufOEgTHrzeyzHLITZu0
      - PHX_SERVER=true
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: '0.5GB'

  api2: 
    build:
      context: .
    hostname: api2
    depends_on:
      - db
    expose:
      - "4000"
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db/rinha_backend_dev
      - SECRET_KEY_BASE=4kZGFFt1SKlRnExAsUKG7aSpJCo2bsyA5smXYNJfe0EbqufOEgTHrzeyzHLITZu0
      - PHX_SERVER=true
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: '0.5GB'

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api1
      - api2
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: '0.5GB'

  db:
    image: postgres:latest
    hostname: db
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - ./ddl.sql:/docker-entrypoint-initdb.d/ddl.sql
    deploy:
      resources:
        limits:
          cpus: '0.15'
          memory: '0.4GB'