name: Elixir CI

on:
  push:
    branches:
      - '*'         # matches every branch that doesn't contain a '/'
      - '*/*'       # matches every branch containing a single '/'
      - '**'        # matches every branch
      - '!main'     # excludes main

jobs:
  build:

    name: Build and test
    runs-on: ubuntu-latest
    env:
      DB_DATABASE: "rinhabackend_test"
      DB_HOSTNAME: "127.0.0.1"
      DB_PASSWORD: "postgres"
      DB_POOL_SIZE: "10"
      DB_PORT: "5432"
      DB_USERNAME: "postgres"
      MIX_ENV: "test"
      SECRET_KEY_BASE: "tS9A8mRSFlXwQY7myvYwoSI4S+Q8S0img+CGPck7bP3kvn8FV78zzYXKnuDhh7cX"

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: "postgres"
          POSTGRES_USERNAME: "postgres"
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
    - uses: actions/checkout@v3

    - name: Set up Elixir

      uses: erlef/setup-elixir@v1
      with:
        elixir-version: '1.14.2' # Define the elixir version [required]
        otp-version: '25.0.3' # Define the OTP version [required]
    - name: Restore dependencies cache
      uses: actions/cache@v2
      with:
        path: deps
        key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
        restore-keys: ${{ runner.os }}-mix-
    - name: Install dependencies
      run: mix deps.get
    - name: Code Beauty
      run: mix format --check-formatted
    - name: Credo
      run: mix credo --strict
    - name: Run tests
      run: mix test